/**: 
  ros__parameters:
    dsm_batch_size: 1
    dsm_class_num: 7
    dsm_conf: 0.5
    device: 0
    dsm_engine_dir: "/home/nvidia/mdl_ws/src/etc/mdl_dsm_model/mdl_dsm_s62.engine"
    dsm_image_sub_topic_name: "/dsm/video_frames"
    dsm_event_topic_name: "/dsm_json_pub"
    dsm_input_h: 640
    dsm_input_w: 640
    dsm_nms: 0.45
    driver_ratio_: 0.4
    head_ratio_: 0.3
    eye_ratio_: 0.8
    mouth_ratio_: 0.8
    call_ratio_: 0.8
    driver_leave_time_: 5.0
    chaoyue_duration_time_: 3.0
    ER_Time: 2.0
    dsm_driver_leave_1: 7.0
    dsm_driver_leave_2: 5.0
    dsm_driver_leave_3: 3.0
    dsm_head_leave_1: 7.0
    dsm_head_leave_2: 5.0
    dsm_head_leave_3: 3.0
    dsm_driver_drown_1: 7.0
    dsm_driver_drown_2: 5.0
    dsm_driver_drown_3: 3.0
    dsm_driver_call_1: 7.0
    dsm_driver_call_2: 5.0
    dsm_driver_call_3: 3.0
    dsm_rtsp_url: "rtsp://admin:bdtd123456@192.168.2.65:554/h265/ch1/main/av_stream"
    car_number: "WLJ3BA"
    dsm_yaml_button: true
    nms_yolo_threshold: 0.45
    conf: 0.50
    nms_pp_threshold: 0.01
    score_threshold: 0.5


    

