/dsm/camera_ros_node:
  ros__parameters:
    url: rtsp://admin:bdtd123456@192.168.1.42:554/h265/ch1/main/av_stream    # 0, rtsp_url,etc
    output_h: 480
    output_w: 640
    image_pub_topic_name: /dsm/video_frames
    log_filedir_prefix: /home/nvidia/datalog/dsm/system_logs/
    rect_x: 0                        # (x,y) represent the upper left corner of image
    rect_y: 0                        # rect represent image
    rect_h: 1080                     #--ros-args -r __node:=camera_ros_node -r __ns:=/dsm --params-file
    rect_w: 1920                     
