demo_pp_yolov5:
  ros__parameters:
    device: 0
    nms_yolo_threshold: 0.45
    conf: 0.50
    class_num: 68
    nms_pp_threshold: 0.01
    score_threshold: 0.8
    x_min: -10.0
    x_max: 10.0
    y_min: -1.0
    y_max: -0.8
    z_min: -0.8
    z_max: 5.0
    pointpillar_onnx_file: /home/nvidia/mdl_ws/src/etc/mdl_adas_model/pointpillar.onnx
    engine_dir: /home/nvidia/mdl_ws/src/etc/mdl_adas_model/best.engine

